language: objective-c
xcode_workspace: EAT.xcworkspace
xcode_scheme: EAT
xcode_sdk: iphonesimulator7.1

before_script:
export LANG=en_US.UTF-8


before_install:
    gem install cocoapods -v '= 0.32.1'
